[runtime]
cudnn_benchmark = true

[loss]
class_balanced_beta = 0.999
use_ce_label_smoothing = true
label_smoothing = 0.01
focal_gamma = 2.0

[training]
epochs = 120
batch_size = 192

[fine_tuning]
epochs = 20

[cross_validation]
n_splits = 3
shuffle = true
random_state = 42

[mixup]
alpha = 0.8
probability = 0.5

[optimization]
lr_cnn = 5e-5
lr_trans = 1e-4
weight_decay = 1e-4

[ema]
decay = 0.999

[checkpoint]
final_model_filename = "last_model_weights.pt"

[reporting]
figure_size = [10, 4]
